
# RadEro R pagkage
# A Compartmental and Physically Based Model to estimate Soil Redistribution Rates using 137Cs Analysis
# EESA group at EEAD-CSIC, Spain

# Sript to Install and Execute RadEro package (version 1.0.5) using an example.
# GitHub link: https://github.com/eead-csic-eesa/RadEro
# created by Arturo Catalá Escamilla | 2024.11.18
# Contact email: radero@eead.csic.es
# Operating system: Windows

# CONTENT OF THIS SCRIPT:
#   1 - INSTALLATION FROM CRAN
#   2 - INSTALLATION FROM GitHub
#   3 - EXAMPLE INPUT FILES: RadEro_example()
#   4 - SOIL REDISTRIBUTION RATE ESTIMATION: RadEro_run()

################################################################################
# 1 - INSTALLATION FROM CRAN
################################################################################

#### STEP 1 | Install the package:
# This will download the latest version of the RadEro package available on CRAN.
# For more details, visit the GitHub repository. https://github.com/eead-csic-eesa/RadEro

  install.packages("RadEro")

#### STEP 2 | Load the package:

  library (RadEro)

################################################################################
# 2 - INSTALLATION FROM GitHub
################################################################################

#### STEP 1 | Download the "RadEro_x.x.x.zip" file.
# Download the latest available version of RadEro from the GitHub repository:
# GitHub link: https://github.com/eead-csic-eesa/RadEro
# Save the file in a directory of your choice.

#### STEP 2 | Set the working directory to the location of "RadEro_x.x.x.zip".

setwd(R"(C:\your\own\directory)")

#### STEP 3 | Load necessary libraries to install the RadEro package.

load_libraries <- function() {
  library(Rcpp)
  library(roxygen2)
  library(usethis)
  library(jsonlite)
  library(data.table)
  library(devtools)
  library(ggplot2)
  library(patchwork)
  library(dplyr)
}
load_libraries()

#### Step 4 | Install RadEro package (Example: version 1.0.5)

install.packages("RadEro_1.0.5.zip")

#### STEP 5 | Load the package:

library (RadEro)


################################################################################
# 3 - EXAMPLE INPUT FILES: RadEro_example()
################################################################################

# The RadEro_example() function creates two files in the specified directory:
# "input-data_example.csv" and "input-config_example.js". These files are simple examples
# that demonstrate how to structure the input data and configuration files for the model.
# We recommend reading the RadEro PROTOCOL available on GitHub (https://github.com/eead-csic-eesa/RadEro)
# to fully understand the parameters within each file. Once you understand these parameters,
# you can use these files as templates for your own projects.
#
# The "input-data_example.csv" and "input-config_example.js" files generated by the
# RadEro_example() function show the construction of these input files.
# The parameter values for "k-samples" and "e-samples" in "input-config_example.js"
# are set to low defaults for quick checks of model functionality, but the resulting
# simulation may not be optimal. For more accurate simulations and redistribution rate
# estimations, increase "k-samples" and "e-samples" to higher values (e.g., "k-samples = 1000"; "e-samples = 1000").


#### STEP 1 | Create a New Working Directory
# For each project, we recommend creating a separate folder. Each project requires
# an input data file and an input configuration file located in the same directory.
# Define your working directory for easier file manipulation:

direct <- R"(C:\your\own\working\directory)"

#### STEP 2 | Create the Example Input Files

RadEro_example(target_dir = direct)

# After reading the PROTOCOL (https://github.com/eead-csic-eesa/RadEro),
# you can complete the "input-data.csv" and "input-config.js" files with your own data.

################################################################################
# 4 - SOIL REDISTRIBUTION RATE ESTIMATION: RadEro_run()
################################################################################

#### STEP 1 | Run the model
# To execute RadEro_run() at a given location, you need both the input data and
# configuration files located in the same directory.
# Using the example files and the previously defined directory:

RadEro_run("input-data_example.csv","input-config_example.js", output_dir = direct)

#### STEP 2 | VISUALIZE the Output Files
# The folder containing plots and the soil redistribution rates in "results.txt"
# will be created in the "direct" directory. To visualize the results file:

results <- read.table(R"(results\results.txt)", header = FALSE, sep = ",")
View(results)


